version: "3.9"
services:
  db:
    container_name: prelo_db
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=
      - POSTGRES_USER=
      - POSTGRES_DB=prelo
    volumes:
      - ./db-data/:/var/lib/postgresql/data
    restart: unless-stopped
